apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  name: dev-admin-db-cluster
spec:
  forProvider:
    region: ap-south-1
    engine: aurora-postgresql
    engineMode: provisioned
    engineVersion: "14.3"
    # scalingConfiguration:
    #   maxCapacity: 2
    #   minCapacity: 1
    enableIAMDatabaseAuthentication: true
    vpcSecurityGroupIDs: SECURITY_GROUP_ID
    dbSubnetGroupName: "dev-workload-db-subnetgroup"
    masterUsername: master
    masterUserPasswordSecretRef:
      name: dev-dbcluster-admin-pwd
      namespace: databases
      key: password
    databaseName: grafana
    applyImmediately: true
    finalDBSnapshotIdentifier: dev-admin-db-cluster
  writeConnectionSecretToRef:
    name: aurora-secrets-dev-admin
    namespace: databases
  providerConfigRef:
    name: default
