apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  name: ENV_NAME-admin-db-cluster
spec:
  forProvider:
    region: REGION
    engine: aurora-postgresql
    engineMode: provisioned
    engineVersion: "14.3"
    # scalingConfiguration:
    #   maxCapacity: 2
    #   minCapacity: 1
    enableIAMDatabaseAuthentication: true
    vpcSecurityGroupIDs: SECURITY_GROUP_ID
    dbSubnetGroupName: "ENV_NAME-workload-db-subnetgroup"
    masterUsername: master
    masterUserPasswordSecretRef:
      name: ENV_NAME-dbcluster-admin-pwd
      namespace: databases
      key: password
    databaseName: grafana
    applyImmediately: true
    finalDBSnapshotIdentifier: ENV_NAME-admin-db-cluster
  writeConnectionSecretToRef:
    name: aurora-secrets-ENV_NAME-admin
    namespace: databases
  providerConfigRef:
    name: default
