apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  name: -microservices-db-cluster
spec:
  forProvider:
    region: 
    engine: aurora-postgresql
    engineMode: provisioned
    engineVersion: "14.3"
    # scalingConfiguration:
    #   maxCapacity: 2
    #   minCapacity: 1
    enableIAMDatabaseAuthentication: true
    vpcSecurityGroupIDs: SECURITY_GROUP_ID
    dbSubnetGroupName: "-workload-db-subnetgroup"
    masterUsername: master
    masterUserPasswordSecretRef:
      name: -microservices-dbcluster-pwd
      namespace: databases
      key: password
    databaseName: auroradb
    applyImmediately: true
    finalDBSnapshotIdentifier: -microservices-db-cluster
  writeConnectionSecretToRef:
    name: aurora-secrets
    namespace: databases
  providerConfigRef:
    name: default
