apiVersion: opensearchservice.aws.crossplane.io/v1alpha1
kind: Domain
metadata:
  name: uat-opensearch-domain
spec:
  deletionPolicy: Delete
  forProvider:
    name: uat-opensearch-domain
    region: ap-southeast-1
    accessPolicies: |
      {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Effect": "Allow",
              "Principal": {
                  "AWS": "*"
              },
              "Action": "es:*",
              "Resource": "arn:aws:es:ap-southeast-1:98764:domain/uat-opensearch-domain/*"
          }
        ]
      }
    advancedSecurityOptions:
      enabled: true
      internalUserDatabaseEnabled: true
      masterUserOptions:
        masterUserName: admin
        masterUserPassword: Password@12345 # UGFzc3dvcmRAMTIzNDU=
    autoTuneOptions:
      desiredState: DISABLED
    clusterConfig:
      coldStorageOptions:
        enabled: false
      dedicatedMasterEnabled: false
      instanceCount: 1
      instanceType: "r6g.large.search"
      warmEnabled: false
      zoneAwarenessEnabled: false
    cognitoOptions:
      enabled: false
    domainEndpointOptions:
      customEndpointEnabled: false
      enforceHTTPS: true
    ebsOptions:
      ebsEnabled: true
      volumeType: gp3
      volumeSize: 50
      iops: 3000
    encryptionAtRestOptions:
      enabled: true
      kmsKeyID: "KEY_ID"
    engineVersion: "OpenSearch_2.3" # upgraded
    nodeToNodeEncryptionOptions:
      enabled: true
    vpcOptions:
      securityGroupIDs: ["SECURITY_GROUP_ID"]
      subnetIDs:
        - SB_UAT1
        - SB_UAT2
        - SB_UAT3
