apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crossplane-system
# - vpc-subnets
- external-secrets
- alb-controller
- appmesh
- api-gateway
- database
- opensearch
# - otel
