apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: alb-controller
spec:
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: eks
  values:
    clusterName: ENV_NAME-workload
    serviceAccount:
      create: false
      name: aws-load-balancer-controller
    vpcId: VPC_ID
