apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::34567:role/AmazonEKSLoadBalancerControllerRole
  name: aws-load-balancer-controller
  namespace: alb-controller
