apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam:::role/-workload-external-secrets-sa-role
  name: external-secrets-sa
  namespace: external-secrets
