apiVersion: eks.aws.crossplane.io/v1beta1
kind: FargateProfile
metadata:
  name: external-secrets
spec: 
  deletionPolicy: "Delete"
  forProvider: 
    clusterName: dev-workload
    podExecutionRoleArn: "arn:aws:iam::34567:role/dev-workload-external-secrets-fp-exec-role"
    region: ap-south-1
    selectors:
      - namespace: external-secrets
    subnets: 
      - SB_DEV1
      - SB_DEV2
      - SB_DEV3
  providerConfigRef:
    name: default
