apiVersion: kustomize.config.k8s.io/v1beta1
Kind: Kustomization

resources:
# - workload-sg.yaml #currently hardcoding ids
- workload-cluster-role.yaml
- workload-cluster-policy-attachment1.yaml
- workload-cluster-policy-attachment2.yaml
- eks-cluster.yaml

# Fargate profile exec roles
- workload-kube-system-fp-exec-role.yaml
- workload-flux-system-fp-exec-role.yaml
- workload-crossplane-system-fp-exec-role.yaml

# Fargate profile role-policy-attachments
- workload-kube-system-fp-exec-role-policy-attachment1.yaml
- workload-kube-system-fp-exec-role-policy-attachment2.yaml
- workload-flux-system-fp-exec-role-policy-attachment.yaml
- workload-crossplane-system-fp-exec-role-policy-attachment.yaml

# Fargate profiles
- workload-fg-profile-kube-system.yaml
- workload-fg-profile-flux-system.yaml
- workload-fg-profile-crossplane-system.yaml

# Addons
- workload-addon-coredns.yaml
- workload-addon-vpc-cni.yaml
- workload-addon-kube-proxy.yaml
