apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: "ENV_NAME-workload-REGION-kube-system-fg-exec-policy-attachment2"
spec:
  deletionPolicy: "Delete"
  forProvider:
    policyArn: "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
    roleName: "ENV_NAME-workload-REGION-kube-system-fp-exec-role"
  providerConfigRef:
    name: default