apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: "ENV_NAME-workload-external-secrets-fp-exec-role"
spec:
  deletionPolicy: "Delete"
  forProvider:
    assumeRolePolicyDocument: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Principal": {
                      "Service": "eks-fargate-pods.amazonaws.com"
                  },
                  "Action": "sts:AssumeRole"
              }
          ]
      }
    description: "ENV_NAME-workload external-secrets fargate pod execution role"
    maxSessionDuration: 3600
  providerConfigRef:
    name: default