apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: "ENV_NAME-workload-external-secrets-sa-policy"
spec:
  deletionPolicy: "Delete"
  forProvider:
    description: "Secrets access policy for external-secrets operator"
    document: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Action": [
                      "secretsmanager:DescribeSecret",
                      "secretsmanager:GetSecretValue",
                      "ssm:DescribeParameters",
                      "ssm:GetParameter",
                      "ssm:GetParameters",
                      "ssm:GetParametersByPath"
                  ],
                  "Effect": "Allow",
                  "Resource": "*"
              },
              {
                  "Action": [
                      "kms:DescribeCustomKeyStores",
                      "kms:ListKeys",
                      "kms:ListAliases"
                  ],
                  "Effect": "Allow",
                  "Resource": "*"
              },
              {
                  "Action": [
                      "kms:Decrypt",
                      "kms:GetKeyRotationStatus",
                      "kms:GetKeyPolicy",
                      "kms:DescribeKey"
                  ],
                  "Effect": "Allow",
                  "Resource": "arn:aws:kms:REGION:ACCOUNT_ID:key/KEY_ID"
              }
          ]
      }
    name: "ENV_NAME-workload-external-secrets-sa-policy"
  providerConfigRef:
    name: default